# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inxxie', '0002_auto_20170921_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.CharField(max_length=255)),
                ('following', models.CharField(max_length=255)),
            ],
        ),
    ]
